# more : https://robotninja.com/blog/introduction-using-selenium-docker-containers-end-end-testing/
version: "3"
services:
  www:
    build:
      context: .
      dockerfile: ./Dockerfile.www
    ports:
      - 8080:8080
    volumes:
      - ./www:/root/app
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
        - default
  php:
      build:
          context: .
          dockerfile: ./Dockerfile.php
      ports:
          - 8081:80
      volumes:
          - ./www:/var/www/html/
          - ./logs:/var/log/apache2/
          - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      networks:
          - default
  tests:
      build:
          context: .
          dockerfile: ./Dockerfile.codeception
      volumes:
          - ./tests:/var/www/tests
          - ./www:/var/www/html
      networks:
          - default
  db:
      image: mariadb
      command: --max_allowed_packet=1073741824
      environment:
          MYSQL_DATABASE: imt2291-proj2
          MYSQL_USER: admin
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      volumes:
          - ./dbInit:/docker-entrypoint-initdb.d
          - persistent:/var/lib/mysql
          - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      networks:
          - default
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8082:80
      environment:
          MYSQL_USER: admin
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          PMA_HOST: db
      volumes: 
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      networks:
          - default
  selenium-hub:
    image: selenium/hub:3.141.59-europium
    container_name: selenium-hub
    networks:
        - default
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:3.141.59-europium
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
  firefox:
    image: selenium/node-firefox:3.141.59-europium
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
volumes:
  persistent:
